---
name: "Build & Test"
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
env:
  GO_VERSION: "~1.23.4"
jobs:
  unit:
    name: "Unit"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "authzed/actions/setup-go@main"
        with:
          go-version: "${{ env.GO_VERSION }}"
      - uses: "magefile/mage-action@v2"
        with:
          version: "latest"
          args: "test:unit"
